### ISSUE TITLE
Text not visible

### ISSUE THREAD

**Issue by schickling** [koajs/logger#26]
I'm using iTerm2 with the Solarized Dark scheme. Unfortunately the output isn't visible (or readable). It looks something like this:

![screen shot 2014-12-15 at 2 22 16 pm](https://cloud.githubusercontent.com/assets/1567498/5436409/28ff0ad4-8466-11e4-9273-4b218068a414.png)

Text is definitely there, proof via text marking:

![screen shot 2014-12-15 at 2 23 57 pm](https://cloud.githubusercontent.com/assets/1567498/5436411/2c191dea-8466-11e4-8f76-4f370dace992.png)

**Comment by niftylettuce** [comment]
https://cabinjs.com is an alternative for now
