### ISSUE TITLE
It should be nice to replace console with own logger API

### ISSUE THREAD

**Issue by yanickrochon** [koajs/logger#31]
For example, using a `winston` instance instead of `console`. And even perhaps specifying the level.

```
app.use(logger({
  logger: winstonInstance,
  level: 'info'
}));
```

Then, instead of `console.log`;

```
opts.logger[opts.level]( ... )
```

Just have the values default to `opts.logger = console` and `opts.level = 'log'`

**Comment by tj** [comment]
ah responded on the PR :D

**Comment by yanickrochon** [comment]
Well, sure, this isn't for production use. However implementing this does not affect latency, is backward compatible, and allow applications to use their own implementation without hijacking `console.log`. 

For example, an app in cluster which `logger` is defined to prepend it's worker id before log messages to inform which worker is processing a request might help debugging race conditions or other async issues. 

For example, when deploying in staging environments, have a logger to report to a file any given error code (params, uri, client info, etc.) without overriding `console.log` and creating other potential issues.

etc.

This is my opinion anyway.

**Comment by yanickrochon** [comment]
My point is, the implementation is trivial; why requiring yet another middleware?

**Comment by tj** [comment]
fair enough, personally I'd do that via a logging system that isn't specific to koa (logstash, fluent etc) but that sounds reasonable

**Comment by sedenardi** [comment]
I created a fork for this exact purpose: https://github.com/sedenardi/koa-external-logger

It exposes the koa context so you can format it and send it wherever you'd like.

**Comment by m4rcelofs** [comment]
+1 for this, since all my logging is already done with `debug` and is nicely formatted/filtered/colored (even if just in dev)

**Comment by coderhaoxin** [comment]
closed by https://github.com/koajs/logger/pull/65
