### ISSUE TITLE
Are there any plans to have an option to store logs in a file?

### ISSUE THREAD

**Issue by sinkingshriek** [koajs/logger#33]
Just curious. Didn't see any while giving a quick glance at the source code.

**Comment by coderhaoxin** [comment]
Maybe, you are looking for

https://github.com/koajs/logger/issues/31
https://github.com/koajs/logger/pull/32

**Comment by sinkingshriek** [comment]
Although the PR somewhat addresses what I was talking about, it's not quite the same. Based on the loglevels (as mentioned in the PR) I think it'd be beneficial to have them write  to a file since almost every production ready project will want to keep backup of them for future use. But now the more I think about it, this feature can be made into a separate middleware as well. Any opinions?

**Comment by coderhaoxin** [comment]
> keep backup of them for future use

this logger is only for development

**Comment by coderhaoxin** [comment]
> this feature can be made into a separate middleware

Yes.

**Comment by sinkingshriek** [comment]
>this logger is only for development

Oh, wow. Do I feel stupid now. I know I read it in the docs but I completely forgot about it when I was actually using it. Thanks, makes sense now.
