### ISSUE TITLE
Non-colored output when under grunt-concurrent

### ISSUE THREAD

**Issue by rbaprado** [koajs/logger#42]
When running under grunt-concurrent, the output is not colored anymore.
- Not happening when running under nodemon only
- On the other hand, only logger has this problem under grunt-conrrent (nodemon, watch, debug, all show their colors)

What additional information may I provide to help diagnosing that?

**Comment by coderhaoxin** [comment]
I'm not using `grunt` 😢 , can you give some codes to reproduce it ?

**Comment by tj** [comment]
If you leap down the rabbit hole you'll eventually get to https://github.com/chalk/supports-color/blob/master/index.js#L41
