### ISSUE TITLE
Incorrect Status Outputs

### ISSUE THREAD

**Issue by wlingke** [koajs/logger#47]
I have a standard koa error catcher like so:

```
async function(ctx, next) {
  try {
    await next();
  } catch (error) {
    ctx.body = { message: "error"};
    ctx.status = 400;
  }
};
```

However, the output log is error status 500 no matter what I set ctx.status to. The client receives the correct status code.

Update: Looks like the code is set to use the `err.status` (such as when set via ctx.throw) rather than `ctx.status` when there is an error.

**Comment by bananaappletw** [comment]
I try this too.
It's true.
Maybe this is some kind related to how koa-logger works.

**Comment by julienw** [comment]
Another issue is when the thrown error is ENOENT, then koa-logger says it's a 500 but koa special-cases this error with a 404 (which is IMO a bit incorrect too).

**Comment by niftylettuce** [comment]
See https://cabinjs.com and its middleware
