### ISSUE TITLE
Logging in Nanoseconds

### ISSUE THREAD

**Issue by nahtnam** [koajs/logger#59]
Hey,

Would like to request the ability to have the option to allow logging in nanoseconds if the response time is under a millisecond. There is `process.hrtime()` in node, and while its relatively inaccurate, it would be great to have the option to have nanosecond outputs.

Thanks.

**Comment by Lizhooh** [comment]
When will it be faster to return below 1ms?

**Comment by niftylettuce** [comment]
See https://cabinjs.com and its middleware
