### ISSUE TITLE
Better not change the Stream ctx.body

### ISSUE THREAD

**Issue by meteorlxy** [koajs/logger#71]
### Desc

I did something like this:

```js
app.use(koaLogger).use(async ctx => {
  ctx.type = 'html'
  ctx.set('Content-Encoding', 'gzip')

  ctx.body = zlib.createGzip({
    flush: zlib.constants.Z_FULL_FLUSH,
  })
  ctx.body.write(Buffer.from('before'))
  setTimeout(() => {
    ctx.body.write(Buffer.from('after some async operation'))
    ctx.body.end()
  }, 1000)
})
```

However, `koa-logger` changes `ctx.body` to `ctx.body.pipe(counter = Counter())`:

https://github.com/koajs/logger/blob/7daa5f401644a7ae396de70874dfa8328e9202d6/index.js#L81-L83

which makes the second `write()` and `end` buggy...

### Workaround

Write into the original stream, instead of `ctx.body`

```js
app.use(koaLogger).use(async ctx => {
  ctx.type = 'html'
  ctx.set('Content-Encoding', 'gzip')

  const gzip = zlib.createGzip({
    flush: zlib.constants.Z_FULL_FLUSH,
  })
  ctx.body = gzip
  gzip.write(Buffer.from('before'))
  setTimeout(() => {
    gzip.write(Buffer.from('after some async operation'))
    gzip.end()
  }, 1000)
})
```

---
### Conclusion

The workaround is simple, but that did make me confused before I read the source code of `koa-logger`.

I would suggest not to modify the `ctx.body` itself.

**Comment by DreadBoy** [comment]
Isn't that expected? You should return promise from your middleware and once that promise is resolved, Koa thinks your middleware did its work. I think correct way to structure your code is:
```js
app.use(koaLogger).use(async ctx => {
  ctx.type = 'html'
  ctx.set('Content-Encoding', 'gzip')

  ctx.body = zlib.createGzip({
    flush: zlib.constants.Z_FULL_FLUSH,
  })
  ctx.body.write(Buffer.from('before'))
  return new Promise(resolve => {
    setTimeout(() => {
      ctx.body.write(Buffer.from('after some async operation'))
      ctx.body.end()
      resolve();
    }, 1000)
  });
})
```

**Comment by niftylettuce** [comment]
See https://cabinjs.com and its middleware
